package it.epicode.CodeCampus.model;

public enum CategoryCourse {
    JAVA, CSHARP, PYTHON, RUBY, PHP, SWIFT, KOTLIN, GO, RUST, SCALA, GROOVY, JAVASCRIPT, TYPESCRIPT, C,
    CPLUSPLUS, PASCAL, COBOL, FORTRAN, ADA, LISP, PROLOG, SCHEME, HASKELL,
    SQL, NOSQL, MONGODB, ORACLE, MYSQL, POSTGRESQL, SQLSERVER, DB2, SYBASE, INFORMIX, TERADATA,
    HTML, CSS, BOOTSTRAP, JQUERY, ANGULAR, REACT, VUE, EMBER, BACKBONE, METEOR, POLYMER, AURELIA, SVELTE,
    SPRING

}
